### ISSUE TITLE
Unnecessary ride fetching

### ISSUE THREAD

**Issue by Ron537** [Lebensmittelgeschaft/Trempiada#22]
https://github.com/Lebensmittelgeschaft/Trempiada/blob/dfb2012494e5b185c11bebcb6b505592dfce77d1/src/ride/ride.controller.ts#L57

Line 57 - no need to fetch ride by id.
Line 59 is enough to know whether this ride exists or not.

Possible change : 

```
const ride = await this.deleteById(id); // If ride doesn't exists this will return null/false
if (ride) {
      ...
}
```

**Comment by omrishtam** [comment]
Removed unnecessary early ride fetch.
