### ISSUE TITLE
Wrong endpoint API (Not restful)

### ISSUE THREAD

**Issue by Ron537** [Lebensmittelgeschaft/Trempiada#23]
https://github.com/Lebensmittelgeschaft/Trempiada/blob/dfb2012494e5b185c11bebcb6b505592dfce77d1/src/user/users.route.ts#L60

This API endpoint (`/user/active/:id`) is not restful and misleading.

Changing it to something like 
`/user/:id/active` - would make it more restful, but not for the purpose you wanted.

For your situation I would consider :
`/user/:id/rides/active` (Might not be the best solution but is better and more accurate than the current one).

**Comment by omrishtam** [comment]
endpoint changed to /user/:id/rides/active
